name: CI & Deploy Staging

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build (simulado)
        run: echo "Nada para compilar, apenas HTML puro."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Test (simulado)
        run: echo "Sem testes automatizados, mas aqui rodariam os testes."

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Move files into staging folder
        run: |
          mkdir staging
          cp index.html staging/
      - name: Deploy to GitHub Pages (staging)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-staging
          publish_dir: ./staging
