name: 🟢 Staging (log on gh-pages push)

on:
  push:
    branches: [ gh-pages ]

permissions:
  contents: read

jobs:
  note:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Push no branch gh-pages detectado. O GitHub Pages publicará /staging automaticamente."