# .github/workflows/deploy-production.yml
name: Deploy Production

on:
  workflow_dispatch:

# Também precisa de permissão de escrita
permissions:
  contents: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Publica a RAIZ do repo na raiz do gh-pages ("/")
      - name: Deploy to GitHub Pages (production)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          keep_files: true          # mantém a pasta /staging já existente
          enable_jekyll: false
